<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoReview.Core\PhotoReview.Core.csproj" />
    <ProjectReference Include="..\PhotoReview.Imaging\PhotoReview.Imaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PhotoReview.Imaging.Tests" />
    <InternalsVisibleTo Include="PhotoReview.Integration.Tests" />
    <InternalsVisibleTo Include="PhotoReview.Benchmark.Cli" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AdobeCompat-v2.icc" LogicalName="PhotoReview.Imaging.Raw.AdobeCompat-v2.icc" />
  </ItemGroup>

</Project>
