using System.Text;
using System.Text.Json;
using PhotoReview.Core.Abstractions;
using PhotoReview.Core.Model;
using PhotoReview.Core.Tests.Fakes;

namespace PhotoReview.Core.Tests.FileActions;

/// <summary>Pure tests of <see cref="JournalCompactionPlan.Build"/> on hand-built and randomly generated byte snapshots.</summary>
public sealed class JournalCompactionPlanTests
{
    private sealed class FakeClock(DateTime utcNow) : IClock
    {
        public DateTime UtcNow { get; set; } = utcNow;
    }

    private static readonly DateTime BaseTime = new(2026, 9, 25, 0, 0, 0, DateTimeKind.Utc);
    private static readonly AppPaths Paths = new(@"C:\Users\test\AppData\Local");

    private static JournalEntry Entry(string id, FileOperationType type, JournalState state, int tick, string? errorCode = null) =>
        new(id, type, state, $@"C:\photos\{id}.jpg", $@"C:\photos\sel\{id}.jpg", 1, BaseTime, BaseTime.AddSeconds(tick),
            Error: errorCode is null ? null : "boom", ErrorCode: errorCode);

    private static byte[] Line(JournalEntry entry) => Encoding.UTF8.GetBytes(JsonSerializer.Serialize(entry) + "\r\n");

    private static byte[] Concat(IEnumerable<byte[]> lines)
    {
        using var ms = new MemoryStream();
        foreach (var line in lines) ms.Write(line);
        return ms.ToArray();
    }

    // ---------------------------------------------------------------------------------------------------------
    // Basic latest-entry-resolution scenarios.
    // ---------------------------------------------------------------------------------------------------------

    [Fact(DisplayName = "Prepared then Committed for the same Id: only Committed is kept")]
    public void Build_PreparedThenCommitted_OnlyCommittedKept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var c = Entry("a", FileOperationType.Copy, JournalState.Committed, 1);
        var bytes = Concat([Line(p), Line(c)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(1, result.DroppedLines);
        Assert.Equal(1, result.KeptLines);
        Assert.Equal(Line(c), result.Kept);
    }

    [Fact(DisplayName = "Prepared-only Id is kept")]
    public void Build_PreparedOnly_Kept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var bytes = Line(p);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(0, result.DroppedLines);
        Assert.Equal(bytes, result.Kept);
    }

    [Fact(DisplayName = "Id whose latest is Failed: both Prepared and Failed are kept")]
    public void Build_PreparedThenFailed_BothKept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var f = Entry("a", FileOperationType.Copy, JournalState.Failed, 1);
        var bytes = Concat([Line(p), Line(f)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(0, result.DroppedLines);
        Assert.Equal(bytes, result.Kept);
    }

    [Fact(DisplayName = "Dismissed (P, F, D): only D is kept")]
    public void Build_PreparedFailedDismissed_OnlyDismissedKept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var f = Entry("a", FileOperationType.Copy, JournalState.Failed, 1);
        var d = Entry("a", FileOperationType.Copy, JournalState.Dismissed, 2);
        var bytes = Concat([Line(p), Line(f), Line(d)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(2, result.DroppedLines);
        Assert.Equal(Line(d), result.Kept);
    }

    [Fact(DisplayName = "Retry (P, F, P, C): only the winning Committed is kept")]
    public void Build_Retry_OnlyCommittedKept()
    {
        var p1 = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var f1 = Entry("a", FileOperationType.Copy, JournalState.Failed, 1);
        var p2 = Entry("a", FileOperationType.Copy, JournalState.Prepared, 2);
        var c = Entry("a", FileOperationType.Copy, JournalState.Committed, 3);
        var bytes = Concat([Line(p1), Line(f1), Line(p2), Line(c)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(3, result.DroppedLines);
        Assert.Equal(Line(c), result.Kept);
    }

    [Fact(DisplayName = "FA-01: P, C, Failed(PendingUnconfirmed) — P is dropped, C and the stale Failed are both kept")]
    public void Build_Fa01ReconcileResidueAfterCommitted_PDroppedCAndFailedKept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var c = Entry("a", FileOperationType.Copy, JournalState.Committed, 1);
        var f = Entry("a", FileOperationType.Copy, JournalState.Failed, 2, JournalErrors.PendingUnconfirmed);
        var bytes = Concat([Line(p), Line(c), Line(f)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(1, result.DroppedLines);
        Assert.Equal(Concat([Line(c), Line(f)]), result.Kept);
    }

    // ---------------------------------------------------------------------------------------------------------
    // Unparseable / blank lines.
    // ---------------------------------------------------------------------------------------------------------

    [Fact(DisplayName = "Unparseable lines (malformed, unknown Type, missing Id) are kept verbatim")]
    public void Build_UnparseableLines_KeptVerbatim()
    {
        var malformed = Encoding.UTF8.GetBytes("{\"Id\":\"x\"\r\n");
        var unknownType = Encoding.UTF8.GetBytes("{\"Id\":\"y\",\"Type\":\"Rename\",\"State\":\"Prepared\",\"Source\":\"C:\\\\y.jpg\"}\r\n");
        var missingId = Encoding.UTF8.GetBytes("{\"Type\":\"Move\",\"State\":\"Prepared\",\"Source\":\"C:\\\\z.jpg\"}\r\n");
        var bytes = Concat([malformed, unknownType, missingId]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(0, result.DroppedLines);
        Assert.Equal(bytes, result.Kept);
    }

    [Fact(DisplayName = "Blank/whitespace-only lines are dropped")]
    public void Build_BlankLines_Dropped()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var blank = Encoding.UTF8.GetBytes("\r\n");
        var whitespace = Encoding.UTF8.GetBytes("   \r\n");
        var bytes = Concat([blank, Line(p), whitespace]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(2, result.DroppedLines);
        Assert.Equal(Line(p), result.Kept);
    }

    [Fact(DisplayName = "A line with an inner '\\r' is never treated as a recognized entry, so its earlier Prepared is kept")]
    public void Build_InnerCarriageReturnInSupersedingLine_EarlierPreparedKept()
    {
        var p = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var c = Entry("a", FileOperationType.Copy, JournalState.Committed, 1);
        var cJson = JsonSerializer.Serialize(c);
        // Inject a raw '\r' right after the opening brace (valid JSON whitespace, but not the line terminator):
        // ReadEntries' StreamReader.ReadLine would split at it, so JournalCompactionPlan must never recognize it as an entry.
        var cWithInnerCr = Encoding.UTF8.GetBytes("{\r" + cJson[1..] + "\r\n");
        var bytes = Concat([Line(p), cWithInnerCr]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(0, result.DroppedLines);
        Assert.Equal(bytes, result.Kept);
    }

    // ---------------------------------------------------------------------------------------------------------
    // Committed-Move tail window.
    // ---------------------------------------------------------------------------------------------------------

    [Fact(DisplayName = "Committed-Move window: only the last 200 (by position) survive despite all being superseded")]
    public void Build_CommittedMoveWindow_OnlyLast200Kept()
    {
        const int ids = 250;
        var lines = new List<byte[]>();
        var committedLines = new byte[ids][];
        for (var i = 0; i < ids; i++)
        {
            var id = $"m{i}";
            var c = Entry(id, FileOperationType.Move, JournalState.Committed, i * 2);
            var d = Entry(id, FileOperationType.Move, JournalState.Dismissed, i * 2 + 1);
            committedLines[i] = Line(c);
            lines.Add(committedLines[i]);
            lines.Add(Line(d));
        }
        var bytes = Concat(lines);

        var result = JournalCompactionPlan.Build(bytes);

        // Dropped: the first 50 Committed lines (ids 0..49) that fell out of the 200-line tail window.
        Assert.Equal(50, result.DroppedLines);
        Assert.Equal(2 * ids - 50, result.KeptLines);
        var keptText = Encoding.UTF8.GetString(result.Kept);
        for (var i = 0; i < 50; i++)
            Assert.DoesNotContain(Encoding.UTF8.GetString(committedLines[i]).TrimEnd(), keptText, StringComparison.Ordinal);
        for (var i = 50; i < ids; i++)
            Assert.Contains(Encoding.UTF8.GetString(committedLines[i]).TrimEnd(), keptText, StringComparison.Ordinal);
    }

    [Fact(DisplayName = "Kept lines preserve original order and exact bytes (CRLF preserved)")]
    public void Build_KeptLines_PreserveOrderAndExactBytes()
    {
        var p1 = Entry("a", FileOperationType.Copy, JournalState.Prepared, 0);
        var c1 = Entry("a", FileOperationType.Copy, JournalState.Committed, 1);
        var p2 = Entry("b", FileOperationType.Move, JournalState.Prepared, 2);
        var f2 = Entry("b", FileOperationType.Move, JournalState.Failed, 3);
        var bytes = Concat([Line(p1), Line(c1), Line(p2), Line(f2)]);

        var result = JournalCompactionPlan.Build(bytes);

        Assert.Equal(Concat([Line(c1), Line(p2), Line(f2)]), result.Kept);
    }

    // ---------------------------------------------------------------------------------------------------------
    // Observational equivalence: compacted must be indistinguishable from the original through every read API.
    // ---------------------------------------------------------------------------------------------------------

    private enum HistoryKind { PreparedCommitted, PreparedFailed, PreparedFailedDismissed, RetryPreparedFailedPreparedCommitted, Fa01Residue }

    private static List<JournalEntry> BuildHistory(string id, FileOperationType type, HistoryKind kind, ref int tickField)
    {
        var tick = tickField;
        JournalEntry Next(JournalState state, string? errorCode = null) => Entry(id, type, state, tick++, errorCode);
        List<JournalEntry> result = kind switch
        {
            HistoryKind.PreparedCommitted => [Next(JournalState.Prepared), Next(JournalState.Committed)],
            HistoryKind.PreparedFailed => [Next(JournalState.Prepared), Next(JournalState.Failed)],
            HistoryKind.PreparedFailedDismissed => [Next(JournalState.Prepared), Next(JournalState.Failed), Next(JournalState.Dismissed)],
            HistoryKind.RetryPreparedFailedPreparedCommitted =>
                [Next(JournalState.Prepared), Next(JournalState.Failed), Next(JournalState.Prepared), Next(JournalState.Committed)],
            HistoryKind.Fa01Residue =>
                [Next(JournalState.Prepared), Next(JournalState.Committed), Next(JournalState.Failed, JournalErrors.PendingUnconfirmed)],
            _ => throw new ArgumentOutOfRangeException(nameof(kind)),
        };
        tickField = tick;
        return result;
    }

    private sealed record GeneratedJournal(byte[] Original, byte[] Compacted, Dictionary<string, List<JournalEntry>> HistoryById);

    private static GeneratedJournal Generate(int seed, int idCount, bool allMoveType)
    {
        var rng = new Random(seed);
        var kinds = Enum.GetValues<HistoryKind>();
        var tick = 0;
        var perId = new Dictionary<string, List<JournalEntry>>(StringComparer.Ordinal);
        var pending = new List<(string Id, Queue<JournalEntry> Queue)>();

        for (var i = 0; i < idCount; i++)
        {
            var id = $"id{i}";
            var type = allMoveType ? FileOperationType.Move : (FileOperationType)(i % 3);
            var kind = kinds[rng.Next(kinds.Length)];
            var history = BuildHistory(id, type, kind, ref tick);
            perId[id] = history;
            pending.Add((id, new Queue<JournalEntry>(history)));
        }

        // Random interleaving that preserves each Id's own append order, plus scattered garbage/blank lines.
        var lines = new List<byte[]>();
        while (pending.Count > 0)
        {
            var index = rng.Next(pending.Count);
            var (id, queue) = pending[index];
            lines.Add(Line(queue.Dequeue()));
            if (queue.Count == 0) pending.RemoveAt(index);

            if (rng.Next(15) == 0) lines.Add(Encoding.UTF8.GetBytes("\r\n")); // blank
            if (rng.Next(15) == 0) lines.Add(Encoding.UTF8.GetBytes($"garbage-{rng.Next()}\r\n")); // unparseable
            _ = id;
        }

        var original = Concat(lines);
        var compacted = JournalCompactionPlan.Build(original).Kept;
        return new GeneratedJournal(original, compacted, perId);
    }

    private static OperationJournal MakeJournal(byte[] bytes, IClock clock)
    {
        var fs = new InMemoryFileSystem();
        fs.AddFile(Paths.JournalFile, bytes);
        return new OperationJournal(Paths, fs, clock);
    }

    [Fact(DisplayName = "Observational equivalence smoke: compacted journal reads identically to the original")]
    public void Build_ObservationalEquivalence_Smoke_AllReadApisAgree() => AssertObservationalEquivalence(seed: 20260900, idCount: 20);

    [Theory(DisplayName = "Observational equivalence: compacted journal reads identically to the original")]
    [InlineData(20260901)]
    [InlineData(20260902)]
    [InlineData(20260903)]
    [Trait("Category", "Slow")]
    public void Build_ObservationalEquivalence_AllReadApisAgree(int seed) => AssertObservationalEquivalence(seed, idCount: 150);

    private static void AssertObservationalEquivalence(int seed, int idCount)
    {
        var generated = Generate(seed, idCount, allMoveType: false);
        var clock = new FakeClock(BaseTime.AddDays(1));

        var original = MakeJournal(generated.Original, clock);
        var compacted = MakeJournal(generated.Compacted, clock);

        Assert.Equal(original.ReadPendingAndFailedOperations(), compacted.ReadPendingAndFailedOperations());
        Assert.Equal(original.ReadPendingOperations().OrderBy(e => e.Id, StringComparer.Ordinal),
            compacted.ReadPendingOperations().OrderBy(e => e.Id, StringComparer.Ordinal));
        Assert.Equal(original.ReadFailedOperations().OrderBy(e => e.Id, StringComparer.Ordinal),
            compacted.ReadFailedOperations().OrderBy(e => e.Id, StringComparer.Ordinal));

        var originalMoves = original.ReadCommittedMoves();
        var compactedMoves = compacted.ReadCommittedMoves();
        AssertIsSubsequence(originalMoves, compactedMoves);

        foreach (var (id, history) in generated.HistoryById)
        {
            var anchors = new List<JournalEntry>(history)
            {
                Entry(id, FileOperationType.Move, JournalState.Prepared, 999_999), // fabricated, never appended
            };
            var preparedOfHistory = history.Where(e => e.State == JournalState.Prepared).ToList();
            var ownSinceOptions = new List<IReadOnlyList<JournalEntry>> { Array.Empty<JournalEntry>() };
            foreach (var prepared in preparedOfHistory) ownSinceOptions.Add([prepared]);
            ownSinceOptions.Add([Entry(id, FileOperationType.Copy, JournalState.Prepared, 999_998)]);

            foreach (var anchor in anchors)
            {
                foreach (var ownSince in ownSinceOptions)
                {
                    var fresh = Entry(id, FileOperationType.Copy, JournalState.Committed, 999_997);
                    var originalOutcome = AppendIfUnchangedSinceFresh(generated.Original, clock, anchor, ownSince, fresh);
                    var compactedOutcome = AppendIfUnchangedSinceFresh(generated.Compacted, clock, anchor, ownSince, fresh);
                    Assert.True(originalOutcome == compactedOutcome,
                        $"Id={id} anchor={anchor.State} ownSince.Count={ownSince.Count}: original={originalOutcome}, compacted={compactedOutcome}");
                }
            }

            var latest = history[^1];
            var older = history[0];
            var (dOrigLatest, sOrigLatest) = DismissFresh(generated.Original, clock, latest);
            var (dCompLatest, sCompLatest) = DismissFresh(generated.Compacted, clock, latest);
            Assert.Equal(dOrigLatest, dCompLatest);
            Assert.Equal(sOrigLatest, sCompLatest);

            if (!ReferenceEquals(older, latest) && older != latest)
            {
                var (dOrigOlder, sOrigOlder) = DismissFresh(generated.Original, clock, older);
                var (dCompOlder, sCompOlder) = DismissFresh(generated.Compacted, clock, older);
                Assert.Equal(dOrigOlder, dCompOlder);
                Assert.Equal(sOrigOlder, sCompOlder);
            }
        }
    }

    /// <summary>Large seed producing a compacted file &gt;= 1 MiB: ReadCommittedMoves must then be exactly equal (not just a subsequence).</summary>
    [Fact(DisplayName = "Observational equivalence at >= 1 MiB: ReadCommittedMoves is exactly equal, not just a superset")]
    [Trait("Category", "Slow")]
    public void Build_ObservationalEquivalence_AtLeastOneMebibyte_ReadCommittedMovesExactlyEqual()
    {
        var generated = Generate(seed: 20260904, idCount: 6000, allMoveType: true);
        Assert.True(generated.Compacted.Length >= 1024 * 1024, $"compacted only {generated.Compacted.Length} bytes; widen the seed");

        var clock = new FakeClock(BaseTime.AddDays(1));
        var original = MakeJournal(generated.Original, clock);
        var compacted = MakeJournal(generated.Compacted, clock);

        Assert.Equal(original.ReadPendingAndFailedOperations(), compacted.ReadPendingAndFailedOperations());
        Assert.Equal(original.ReadCommittedMoves(), compacted.ReadCommittedMoves());
    }

    private static void AssertIsSubsequence(IReadOnlyList<JournalEntry> shorter, IReadOnlyList<JournalEntry> longer)
    {
        var j = 0;
        foreach (var entry in shorter)
        {
            while (j < longer.Count && longer[j] != entry) j++;
            Assert.True(j < longer.Count, $"entry {entry.Id}/{entry.State} of the original result is missing from the compacted result");
            j++;
        }
    }

    private static bool AppendIfUnchangedSinceFresh(byte[] bytes, IClock clock, JournalEntry anchor, IReadOnlyList<JournalEntry> ownSince, JournalEntry entry)
    {
        var journal = MakeJournal(bytes, clock);
        return journal.AppendIfUnchangedSince(anchor, ownSince, entry);
    }

    private static (IReadOnlyList<JournalEntry> Dismissed, IReadOnlyList<JournalEntry> Skipped) DismissFresh(byte[] bytes, IClock clock, JournalEntry entry)
    {
        var journal = MakeJournal(bytes, clock);
        var outcome = journal.Dismiss([entry]);
        return (outcome.Dismissed, outcome.Skipped);
    }
}
